title: Vinit Kumar
theme: jekyll-theme-minimal
logo: /images/IMG_8292-EDIT__1_-removebg-preview.png
description: Welcome to the personal website of Vinit Kumar, an Impact Investment Financial Analyst at Microsoft. Explore my portfolio, blog, and contact information.
author: Vinit Kumar
