# _config.yml
title: Vinit Kumar
theme: jekyll-theme-minimal
logo: C:/Users/kumarvin/Downloads/IMG_8292-EDIT/
description: Welcome to the personal website of Vinit Kumar, an Impact Investment Financial Analyst at Microsoft. Explore my portfolio, blog, and contact information.
author: Vinit Kumar
